---
title: "Practice Exam 1"
output: html_document
---
```{r}
# install libraries 
library(raster)
library(here)
library(tidyverse)
library(sf)
library(tmap)
library(janitor)
library(broom)
library(sp)
library(spdep)

# load data 
graffiti <- read_csv(here("Practice Exam Q", "Graffiti.csv"))
sanfranshape <- read_sf(here::here("Practice Exam Q", "Census 2010_ Tracts for San Francisco", "geo_export_ce2f7637-eaaf-41cc-87f7-2df773f71874.shp")) %>%
  st_transform(., crs = 7131) # transforming into a projected CRS

# separate the grafitti points into two columbs for latitude and longitude 
graffiti2<-graffiti%>%
  separate(., Point, c("A", "B"), sep = ",")

graffiti2$A<-parse_number(graffiti2$A) # removes any non-numeric characters, and returns a numeric value
graffiti2$B<-parse_number(graffiti2$B)

# changing csv into shapefile
graffiti3 <- graffiti2 %>%
  filter(A != 0) %>%
  filter(B != 0) %>%
  st_as_sf(., coords = c("B", "A"),
           crs = 4326)

graffiti4 <- graffiti3 %>%
  filter(str_detect(Closed, "2019")) %>% 
  st_transform(., crs = 7131)

# filter data to make sure it falls within shapefile boundaries
graffiti_within <- graffiti4[sanfranshape, , op = st_intersects]

# produce a basic plot of our data
tmap_mode("plot")
tm_shape(sanfranshape) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(graffiti4) +
  tm_dots(col = "blue")
```

```{r}
# merge the data 
sfgraffiti <- sanfranshape%>%
  st_join(graffiti4)%>%
  add_count(geoid10)%>%    
  janitor::clean_names()%>%
  #calculate area
  mutate(area=st_area(.))%>%
  #then density of the points per ward
  mutate(density=n/area)%>%
  dplyr::select(geoid10 , neighborhood, density)%>%
  group_by(geoid10) %>%         
summarise(geoid10 = first(geoid10),
          neighborhood= first(neighborhood),
          density= first(density))
```

Having loaded in our data and cleaned it, we can now perform our analysis 
